"""empty message

Revision ID: c6a42217189b
Revises: 43c3c90b98a4
Create Date: 2025-03-24 10:34:19.997673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a42217189b'
down_revision = '43c3c90b98a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_travel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kilometers_traveled', sa.Float(), nullable=False))
        batch_op.alter_column('fuel_efficiency',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('kilometer_traveled')

    with op.batch_alter_table('energy_usage', schema=None) as batch_op:
        batch_op.alter_column('electricity_bill',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('natural_gas_bill',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('fuel_bill',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.alter_column('waste_generated',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('recycling_percentage',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.alter_column('recycling_percentage',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('waste_generated',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('energy_usage', schema=None) as batch_op:
        batch_op.alter_column('fuel_bill',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('natural_gas_bill',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('electricity_bill',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('business_travel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kilometer_traveled', sa.FLOAT(), nullable=True))
        batch_op.alter_column('fuel_efficiency',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('kilometers_traveled')

    # ### end Alembic commands ###
